### PR TITLE
Deadlock fixes

### PR DESCRIPTION
**Pull request by Bertg**
We have been having several deadlock issue son or JenkinCI instance in the last couple of weeks.
This can always be traced back to this plugin. Now it's not clear where to report this issue, let alone trying to suggest a fix, so I'm doing it through this PR.

Note: I am not a JAVA developer, and I took this code from an other repo through cherry-picks.

Would be very nice if @apachelogger could give his 2 cents on how well these changes have worked for him. 

If there is some other way to report this, or suggest these changes; please let me know.

### CODE REVIEW

**Comment by apachelogger** [comment]
Been working fine. The problem is ultimately that addNode is protected but removeNode (happens in the Node class I think), so if/when node provisioning fails the node gets removed in an unprotected fashion and you get a lock conflict because adding a node and removing a node both claim Jenkins' queue lock to refresh label availability (which will eventually call canProvision, which too needs the provision lock). So, what eventually happens is that one thread has the queue lock and the other thread has the provision lock and one cannot proceed because canProvison cannot claim the lock and without canProvision finishing the queue lock never becomes available.
Having looked at a whole bunch of cloud plugins it seems most do not actually fully qualify "provisionability" in canProvision, but instead handle it as a "do I know what to do with the label in general" kind of affair and essentially defer the "are we actually allowed to provision" decision to the actual provision call. This seems to work well for DO as well. Mind you, I do not find the changes I did pretty, the obvious downside of the lock removal and ignoring the cap is that now Jenkins spams provision calls even when the instance cap is reached, because the plugin always says it can provision even when the cap is already reached. So this can cause much more CPU consumption as jenkins will constantly try to provision and DO constantly errors because it has hit the cap.

The "nice" solution may well be to refactor the code so removing a node can be covered by the provision lock.

**Comment by Bertg** [comment]
> So this can cause much more CPU consumption as jenkins will constantly try to provision

High CPU consumption still beats a DEVOPS person having to restart Jenkins every couple of days

>  the obvious downside of the lock removal and ignoring the cap is that now Jenkins spams provision calls even when the instance cap is reached

Oh, so this means that with these changes there is NO cap management at all in Jenkins?

**Comment by apachelogger** [comment]
There is cap management, it just happens in provision() instead of canProvision() which is why Jenkins will repeatedly call provision() as it doesn't quite know when the cap is reached and "provisionability" is lost. That is to some degree always the case though, when 300 jobs start all at once but there is a cap of 50 nodes jenkins would repeatedly run provision despite having reached cap already because Jenkins itself has no understanding of the cap, it only knows if a cloud plugin can or cannot provision a given label.

**Comment by Bertg** [comment]
Yeah, I found [the line](https://github.com/jenkinsci/digitalocean-plugin/blob/ebf1723ff6d9ee1ac67f14603e9fa3bac5caf65e/src/main/java/com/dubture/jenkins/digitalocean/SlaveTemplate.java#L244)

As long as the plugin manages the cap "somehow", then I think the tradeoff of CPU usage vs Deadlock is a good one to make.

Now let's hope that the maintainers of this plugin notice this PR :)

**Comment by anpieber** [comment]
Noticed it. I'll review, test and release the patch during the week end.

Kind regards,
Andreas

Am Fr., 7. Dez. 2018, 15:56 hat Bert Goethals <notifications@github.com>
geschrieben:

**Comment by Bertg** [comment]
Just one more question. Where is the "right" place to open or see tickets for this plugin?

**Comment by anpieber** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-45003?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20digitalocean-plugin might be the correct location, but TBH I'm really limited on time and the plugin does work for me as it is. So if you have any troubles with the plugin or have good ideas for improvements, best provide a pull request, instead of an issue :-)

**Comment by Bertg** [comment]
This has been running in production for a month now. So I thought I'd give a little update.

* We have had NO deadlock issues, and Jenkins just "feels" great.
* All droplets created by Jenkins get cleaned up all the time
* CPU usage and Load have not really been affected very much in our case
* Our Digital Ocean cost has gone up though. Basically because we are able to more run test more reliably :)

So, all and all, this has been a great change!

**Pull request merged**
